draw_text(20, 20, string(global.potato))
draw_text(20, 50, string(global.money))
draw_text(20, 80, string(global.cooked_potato))
draw_text(20, 110, string(global.fatigue))
draw_text(20, 140, string(global.hunger))
draw_text(20, 140, string(global.hunger))
/*draw_set_alpha(alpha)
draw_set_colour(color)
draw_rectangle(0, 0, width, height, 0)
draw_set_alpha(1)
draw_set_colour(c_white)*/